/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

public class App {
    /**
     * greetings.
     * @return hello world
     */
    public String getGreeting() {
        return "Hello World!";
    }

    /**
     * main class of the application.
     * @param args args.
     */
    public static void main(final String[] args) {
        System.out.println(new App().getGreeting());
    }
}
