/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import java.util.List;
import java.io.FileReader;

import com.opencsv.bean.CsvToBeanBuilder;

import org.example.entities.Row;
import org.example.ui.UI;

public final class App {

    /**
     * Private constructor.
     */
    private App() {

    }

    /**
     * main class of the application.
     * @param args args.
     */
    public static void main(final String[] args) {
        List<Row> beans = null;
        try {
            beans = new CsvToBeanBuilder<Row>(new FileReader("temp.csv"))
                    .withSeparator(';')
                    .withType(Row.class)
                    .build()
                    .parse();
        } catch (Exception e) {
            e.printStackTrace();
        }

        if (beans == null) {
            return;
        }

        System.out.println(beans.get(1));

        UI.passDataAndLaunch(beans);
    }
}
